export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
export const ACCOUNT_SHOW_SIGNUP= 'ACCOUNT_SHOW_SIGNUP';
export const ACCOUNT_SHOW_SIGNUP_RESET = 'ACCOUNT_SHOW_SIGNUP_RESET';
export const ACCOUNT_SIGNUP_FAILURE = 'ACCOUNT_SIGNUP_FAILURE';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';
export const ACCOUNT_RETRIEVE_EMPTY = 'ACCOUNT_RETRIEVE_EMPTY';
export const ACCOUNT_LOGIN_REDIRECTED = 'ACCOUNT_LOGIN_REDIRECTED';
export const ACCOUNT_LOGIN_RETURN = 'ACCOUNT_LOGIN_RETURN';
export const ACCOUNT_REGISTER_RETURN = 'ACCOUNT_REGISTER_RETURN';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';
export const ACCOUNT_HIDE_HEADERLOGIN = 'ACCOUNT_HIDE_HEADERLOGIN';
export const ACCOUNT_CONFIRMATION_EMAIL_SENT = 'ACCOUNT_CONFIRMATION_EMAIL_SENT';
export const ACCOUNT_CONFIRMATION_EMAIL_FAILURE = 'ACCOUNT_CONFIRMATION_EMAIL_FAILURE';
export const ACCOUNT_CONFIRMATION_EMAIL_SUCCESS = 'ACCOUNT_CONFIRMATION_EMAIL_SUCCESS';
export const ACCOUNT_CONFIRMATION_EMAIL_SENT_CLEAR = 'ACCOUNT_CONFIRMATION_EMAIL_SENT_CLEAR';
export const ACCOUNT_FORGOT_PASSWORD_FAILURE = 'ACCOUNT_FORGOT_PASSWORD_FAILURE';
export const ACCOUNT_FORGOT_PASSWORD_SUCCESS = 'ACCOUNT_FORGOT_PASSWORD_SUCCESS';
export const ACCOUNT_FORGOT_PASSWORD_RETURN = 'ACCOUNT_FORGOT_PASSWORD_RETURN';
export const ACCOUNT_RESET_PASSWORD_FAILURE = 'ACCOUNT_RESET_PASSWORD_FAILURE';
export const ACCOUNT_RESET_PASSWORD_SUCCESS = 'ACCOUNT_RESET_PASSWORD_SUCCESS';
export const ACCOUNT_RESET_PASSWORD_RETURN = 'ACCOUNT_RESET_PASSWORD_RETURN';
export const ACCOUNT_UPDATE_FSLOGIN = 'ACCOUNT_UPDATE_FSLOGIN';

export const BITE_ADD_SUCCESS = 'BITE_ADD_SUCCESS';
export const BITE_ADD_CLEAR = 'BITE_ADD_CLEAR';
export const BITE_FETCH_INPROGRESS = 'BITE_FETCH_INPROGRESS';
export const BITE_GET_INITIALLOAD_SUCCESS = 'BITE_GET_INITIALLOAD_SUCCESS';
export const BITE_GET_SUCCESS = 'BITE_GET_SUCCESS';
export const BITE_GET_FAILURE = 'BITE_GET_FAILURE';
export const BITE_POST_SUCCESS = 'BITE_POST_SUCCESS';
export const BITE_POST_FAILURE = 'BITE_POST_FAILURE';

export const FEEDFORM_QUERYVENUE_SUCCESS = 'FEEDFORM_QUERYVENUE_SUCCESS';
export const FEEDFORM_QUERYVENUE_FAILURE = 'FEEDFORM_QUERYVENUE_FAILURE';

export const LOAD_STATEPROVINCES_SUCCESS = 'LOAD_STATEPROVINCES_SUCCESS';

//export const MENU_SUCCESS = 'MENU_SUCCESS';
//export const MENU_FAILURE = 'MENU_FAILURE';

export const PROFILE_RETRIEVE_SUCCESS = 'PROFILE_RETRIEVE_SUCCESS';
export const PROFILE_RETRIEVE_FAILURE = 'PROFILE_RETRIEVE_FAILURE';
export const PROFILE_FOLLOW_SUCCESS = 'PROFILE_FOLLOW_SUCCESS';
export const PROFILE_FOLLOW_FAILURE = 'PROFILE_FOLLOW_FAILURE';
export const PROFILE_UNFOLLOW_SUCCESS = 'PROFILE_UNFOLLOW_SUCCESS';
export const PROFILE_UNFOLLOW_FAILURE = 'PROFILE_UNFOLLOW_FAILURE';

export const SEARCHBAR_SUCCESS = 'SEARCHBAR_SUCCESS';
export const SEARCHBAR_RESULTS_FOUND = 'SEARCHBAR_RESULTS_FOUND';
export const SEARCHBAR_RESULTS_EMPTY = 'SEARCHBAR_RESULTS_EMPTY';
export const SEARCHBAR_QUERYUSERNAME_SUCCESS = 'SEARCHBAR_QUERYUSERNAME_SUCCESS';
export const SEARCHBARHISTORY_SUCCESS = 'SEARCHBARHISTORY_SUCCESS';
export const SEARCHBAR_FAILURE = 'SEARCHBAR_FAILURE';
export const SEARCHBAR_CLEARALGOLIA = 'SEARCHBAR_CLEARALGOLIA';

export const WALLFEED_FETCH_INPROGRESS = 'WALLFEED_FETCH_INPROGRESS';
export const WALLFEED_GET_SUCCESS = 'WALLFEED_GET_SUCCESS';
export const WALLFEED_GET_FAILURE = 'WALLFEED_GET_FAILURE';